name: corelojaapp
description: Aplicação de Loja Online.

publish_to: 'none' 

version: 0.4.4

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  get: ^3.24.0
  get_test: ^3.13.3
  equatable: ^1.2.5
  cloud_firestore_mocks: ^0.5.0+1
  firebase_auth_mocks: ^0.3.2
  google_sign_in_mocks: ^0.1.0+2
  firebase_core: ^ 0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.1
  google_sign_in: ^4.5.4
  rxdart: ^0.24.1
  connectivity: ^0.4.9+3
  image_picker: ^0.6.7+11
  flutter_staggered_grid_view: ^0.3.2
  url_launcher: ^5.4.10
  path_provider: ^1.6.10
  transparent_image: ^1.0.0
  carousel_pro: ^1.0.0
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  
  retorno_sucesso_ou_erro_package:
    git: https://github.com/pwlimaverde/retorno_sucesso_ou_erro_package
  
  

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
   
  uses-material-design: true

 
